### ISSUE TITLE
Documentation is a very valuable as a map.

### ISSUE THREAD

**Issue by val922** [dguzzo/flickr-masonry#18]
Salute, I'm attempting to update your upload but its undocumented, regardless, its a good contribution. Maybe point me to the documentation if there is.

**Comment by dguzzo** [comment]
Hi @val922, you're absolutely correct. I wish I had documented this project better, but I didn't. It's quite old now, and is decommissioned for all intents and purposes. I'm just leaving it up for historical reasons. Thanks for your comment/issue.

**Comment by val922** [comment]
much appreciate the clarification. Thank you!
